### PR TITLE
Implement serialization

### PR DESCRIPTION
**Pull request by TopHatCroat**
Hi again,

I've implemented serialization into this library I've been using this for quick and simple scripts which work with JSON:API backend without issue.

The thing that I changed was that for the JSON:API `type` I've used `$type` as a key instead, simply because you can have a `type` attribute.

If you think this implementation is good enough and makes sense I'll add some documentation also.

### CODE REVIEW

**Comment by noplay** [comment]
Great ! I will be happy to merge it if you add documentation. 

Also if you can add you to the contributors section in the README

**Comment by TopHatCroat** [comment]
I've updated the documentation, bit later then I would like, but I had a frantic week.
If you have any more suggestions or ideas, please do mention it.

**Comment by noplay** [comment]
I'm so sorry to have been so slow to merge :(

A 0.7 is now available. 

Thank you so much

**Comment by TopHatCroat** [comment]
No problem, glad to contribute 😋

**Pull request merged**
